### ISSUE TITLE
Children processing

### ISSUE THREAD

**Issue by VincTheSecond** [udapi/udapi-python#22] opened 2016-12-16 15:15 UTC
Let's continue in the discussion about manipulation with the `node.children` from the PR #18...

Accessing a list of children using `node.children` seems to be without problems, so let's discuss about the `node.children` as a setter. Before we remove this setter, we must handle 2 usages in the project:

### Setting a new parent
When setting a new parent for the node `A` (e.g. from `B` to `C`), we must:
- remove `A` from `B.children`
- add `A` to `C.children`

Both `B.children` and `C.children` should stay ord-ordered.

Note, that for adding `A` to `C.children` we cannot use `set_parent` because in this method we need to add `A` to `C.children` :-)

### Removing node
Before the removing the current node, we must remove the current node from the `node.parent.children`.

**Comment by VincTheSecond** [comment] 2016-12-16 15:18
Actually, my only idea how to solve it is to introduce two new methods:
- `remove_child()`
- `add_child()`

Adding a new children can check cycles and other stuff as `set_parent` does.

**Comment by martinpopel** [comment] 2016-12-17 01:09
> so let's discuss about the node.children as a setter

Last time I suggested `nodeA.children = nodesB` could be a shortcut for

```python
for nodeB in nodesB:
    nodeB.parent = nodeA
```

The problem is what to do if `nodeA` already had some children:
* delete them without any warning (that's very dangerous I think)
* keep them (but then the semantics of `nodeA.children = nodesB` is twisted)
* raise an exception (but then such setter would be almost useless)
Thus I am against implementing such setter (both `nodeA.children = nodesB` and `nodeA.set_children(nodesB)`).
We could implement method `add_children`, but I don't think there is a need for such method.

**Comment by martinpopel** [comment] 2016-12-17 01:36
> Before we remove this setter, we must handle 2 usages in the project:

The two usages I found are in `node.py` itself and should be converted to `_children`.
That's how it was done in the original implementation before [this commit](https://github.com/udapi/udapi-python/commit/f8427e7bbf3d833ebbb84fd2b5c34819c1bf24b1#diff-af190b785830a35b661831eb9bbe8c1aL105).
The underscore means it is a private property which should be used only from udapi.core (ideally only from udapi.core.node and its possible derived classes).

> remove_child()
> add_child()

I don't think we need these methods.
* `nodeA.remove_child(nodeB)` can be substituted with `nodeB.parent = undef`. Another question is whether we want to allow such nodes without any parent in usual code. E.g. in Treex it is forbidden. In Perl Udapi it is used in speed-critical parts of loading CoNLLU.
* `nodeA.add_child(nodeB)` can be substituted with `nodeB.set_parent(nodeA)`.

**Comment by martinpopel** [comment] 2016-12-17 02:06
I think, we can close this issue. The only question which remains is whether to have `set_parent` or parent as setter.
* `nodeA.set_parent(nodeB)` is more [consistent with the Java and Perl API](https://htmlpreview.github.io/?https://github.com/udapi/udapi-common/blob/master/doc/comparison.html).
* `nodeA.parent = nodeB` is maybe more Pythonic.
In Python, there should be one--_and preferably only one_--obvious way to do it. So we need to choose which of these two.

I'm slightly more inclined towards the latter, which is the current state. This is one of the few Udapi Python methods with `set_` in name (and `root.set_zone(X)` has been changed to `root.zone = X` as well).

**Comment by VincTheSecond** [comment] 2016-12-17 11:25
> The two usages I found are in `node.py` itself and should be converted to `_children`.

That's true, I did not realize that. So I am going to remove the children setter and modify the `node.py` to use `_children` directly...

**Comment by VincTheSecond** [comment] 2016-12-17 11:29
> The only question which remains is whether to have set_parent or parent as setter.

I do not prefer any style, but we should be consistent. So if we introduce the `set_parent`, I propose to introduce methods like `set_lemma()`, `set_deperl()`, ... as well.

**Comment by martinpopel** [comment] 2016-12-19 10:00
@zabokrtsky agrees with `nodeA.parent = nodeB`, so I am closing this issue.

**Closed by martinpopel** 2016-12-19 10:00 UTC
